const fs = require('fs');
const base = 'C:/Users/elieu/OneDrive/Desktop/biofinaltest/';

// unit1 #20 - hypothesis vs scientific theory (1.3 p7 + p12)
const u1 = JSON.parse(fs.readFileSync(base+'unit1_questions.json','utf8'));
u1[20] = {
  section:'1.3', title:'The Process of Science', t:'mc',
  q:'According to Unit 1.3, what is the key distinction between a hypothesis and a scientific theory?',
  a:2,
  opts:[
    'A hypothesis is used only in controlled experiments, while a theory is based on observation alone.',
    'A theory is an early, untested explanation, while a hypothesis has been tested and confirmed.',
    'A hypothesis is a testable explanation for a specific observation, while a scientific theory is broader in scope and supported by a large, growing body of evidence.',
    'A theory explains only biological phenomena, while a hypothesis can apply to any scientific discipline.'
  ],
  explanation:'According to Unit 1.3, a hypothesis is a possible, testable explanation for a natural event — an informed statement, not merely a guess, that can be tested using the scientific method. A scientific theory, by contrast, is much broader in scope than a hypothesis and is supported by a large and usually growing body of evidence. The Theory of Evolution and the Cell Theory are given as examples of fundamental theories. Option A is incorrect because hypotheses are formed before experiments begin, not exclusively used within them. Option B reverses the relationship — theories are not early or untested; they represent the most well-supported explanations in science. Option D is incorrect because the notes do not limit theories to biology only.'
};
fs.writeFileSync(base+'unit1_questions.json', JSON.stringify(u1,null,2));
console.log('unit1 #20 done');

// unit3 #0 - Cell Theory 3rd tenet (3.1 p5)
const u3 = JSON.parse(fs.readFileSync(base+'unit3_questions.json','utf8'));
u3[0] = {
  section:'3.1', title:'Cell Biology', t:'mc',
  q:'According to Cell Theory as stated in Unit 3.1, which of the following correctly describes how new cells are formed?',
  a:1,
  opts:[
    'New cells can spontaneously arise from nonliving organic material under the right chemical conditions.',
    'New cells arise only from the reproduction of existing cells.',
    'Cells are generated by the immune system whenever tissues are damaged and need repair.',
    'New cells form by the self-assembly of proteins and lipids in the surrounding cytosol.'
  ],
  explanation:'The third tenet of Cell Theory — established through the work of Hooke, Leeuwenhoek, Schleiden, Schwann, and Virchow between the 16th and 19th centuries — states that cells come only from the reproduction of existing cells. This is also called the principle of biogenesis. Option A describes spontaneous generation, which was disproved. Option C is incorrect because immune cells arise by cell division from existing cells, not from nonliving material. Option D describes molecular self-assembly, which is a different process and does not constitute the formation of a new cell.'
};
fs.writeFileSync(base+'unit3_questions.json', JSON.stringify(u3,null,2));
console.log('unit3 #0 done');

// unit4 #67 - hemizygous X-linked recessive (4.9 p18-19)
const u4 = JSON.parse(fs.readFileSync(base+'unit4_questions.json','utf8'));
u4[67] = {
  section:'4.9', title:'Mendelian Inheritance P2 - Genetic Disorders', t:'mc',
  q:"Morgan's team observed that white eye color in Drosophila appeared only in male offspring, never in females, even though overall inheritance ratios matched autosomal patterns. What explains this result?",
  a:3,
  opts:[
    'White eye color is autosomal dominant; females are protected by a second copy of the autosome.',
    'The Y chromosome carries a dominant red-eye allele that overrides the white-eye allele in males.',
    'Females produce a developmental hormone that suppresses X-linked recessive traits from being expressed.',
    'White eye color is X-linked recessive; males are hemizygous (only one X chromosome) and express whatever allele is present, while females require two copies of the recessive allele to show the trait.'
  ],
  explanation:"White eye color in Drosophila is an X-linked recessive trait. Males have only one X chromosome (XY), making them hemizygous — they express whichever allele is on their single X with no second copy to mask it. Females (XX) need two copies of the recessive white-eye allele to express the trait; a single copy is masked by the dominant red-eye allele on the other X. This is why Morgan's team saw only males with white eyes even though overall ratios followed the 3:1 pattern of regular autosomal dominance. The Y chromosome does not carry X-linked genes at all. Option A is incorrect because the white-eye gene is X-linked, not autosomal. Option C is incorrect; no such hormonal mechanism is described in the notes."
};
fs.writeFileSync(base+'unit4_questions.json', JSON.stringify(u4,null,2));
console.log('unit4 #67 done');

// unit5 #0 - evolution as unifying principle (5.1 p4)
const u5 = JSON.parse(fs.readFileSync(base+'unit5_questions.json','utf8'));
u5[0] = {
  section:'5.1', title:'Darwin & Evidence for Evolution', t:'mc',
  q:"Unit 5.1 describes evolution as the 'unifying principle of biology.' Which statement best explains what this means?",
  a:0,
  opts:[
    'Evolution explains both the similarities among living organisms (reflecting common ancestry) and the diversity of life (as populations adapted to different environments over time).',
    'Evolution applies only to animals, providing a single framework that explains all animal anatomy and behavior.',
    'Evolution is the only biological theory with no known exceptions, making it the single most testable claim in science.',
    'Evolution unifies biology by showing that all organisms alive today emerged simultaneously from one common ancestor event.'
  ],
  explanation:"According to the Unit 5.1 notes, evolution is called the unifying principle of biology because it simultaneously explains the unity of life (similarities between living things reflect common ancestors) and the diversity of life (each lineage has adapted to a particular way of life). This dual explanatory power is what makes it foundational to all of biology rather than just one subfield. Option B is incorrect because evolution applies to all life, not only animals. Option C is incorrect — the notes do not claim evolution has no exceptions, and that is not the reason it is considered a unifying principle. Option D is incorrect because evolution describes gradual divergence over time from common ancestors, not a single simultaneous origin event."
};
fs.writeFileSync(base+'unit5_questions.json', JSON.stringify(u5,null,2));
console.log('unit5 #0 done');

// unit6 #0 - viruses not living (6.1 p3)
// unit6 #7 - prokaryote structure (6.2 p4)
const u6 = JSON.parse(fs.readFileSync(base+'unit6_questions.json','utf8'));
u6[0] = {
  section:'6.1', title:'Viruses', t:'mc',
  q:'According to Unit 6.1, why are viruses NOT classified as living organisms?',
  a:1,
  opts:[
    'Viruses are too small to carry out any chemical reactions, making life classification impossible.',
    'Viruses lack metabolism and cannot respond to stimuli, and they require the machinery of a host cell to replicate rather than reproducing independently.',
    'Viruses are composed only of protein with no nucleic acids, so they cannot store or transmit genetic information.',
    'Viruses cannot evolve because they lack DNA, keeping their structure unchanged across generations.'
  ],
  explanation:'The Unit 6.1 notes explicitly state that viruses are not considered living because they do not have metabolism and cannot respond to stimuli. Additionally, they require the machinery of a host cell to replicate — they cannot reproduce independently. Option A is incorrect because size alone does not determine whether something is classified as living. Option C is incorrect because viruses do contain nucleic acids (either DNA or RNA) within their capsid as their inner core of genetic material. Option D is incorrect because the notes explicitly state that viruses are able to evolve as a result of mutations, confirming that they have a genome capable of change over time.'
};
u6[7] = {
  section:'6.2', title:'Prokaryotes', t:'mc',
  q:'Which structural feature, according to Unit 6.2, is shared by ALL prokaryotes and distinguishes them from eukaryotes?',
  a:2,
  opts:[
    'Prokaryotes have a membrane-bound nucleus that protects their DNA from cytoplasmic enzymes.',
    'Prokaryotes contain chloroplasts and mitochondria that enable photosynthesis and cellular respiration.',
    'Prokaryotes lack a membrane-bounded nucleus (with DNA concentrated in a nucleoid region) and lack membranous organelles.',
    'Prokaryotes reproduce exclusively by conjugation, passing DNA through a sex pilus to neighboring cells.'
  ],
  explanation:'According to Unit 6.2, prokaryotes are defined by the absence of a membrane-bounded nucleus — DNA is instead found in a region called the nucleoid — and by the absence of membranous organelles. These two features together are the fundamental structural distinction from eukaryotes. Option A is the exact opposite of the defining characteristic; prokaryotes lack a membrane-bound nucleus, not have one. Option B is incorrect because chloroplasts and mitochondria are membrane-bound organelles, which prokaryotes do not possess. Option D is incorrect because while conjugation is one method of genetic recombination, the primary reproductive mode of prokaryotes is binary fission, not conjugation.'
};
fs.writeFileSync(base+'unit6_questions.json', JSON.stringify(u6,null,2));
console.log('unit6 #0 and #7 done');
console.log('All 6 questions rewritten.');
